name: Release

on:
  push:
    branches:
      - main  # Only run on main branch pushes (PR merges)
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

permissions: {}

jobs:
  release-pr:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
    runs-on: ubuntu-latest
    outputs:
      release_pr: ${{ toJSON(steps.release-pr.outputs) }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Verify actionutils/create-release-pr
        uses: actionutils/trusted-tag-verifier@68bef2f18f8ceb5c4dccc5542cadcfbc82ed4656 # v0.5.0
        with:
          verify: 'actionutils/create-release-pr'
      - name: Create or update release PR
        id: release-pr
        uses: actionutils/create-release-pr@v0

  verify-releaser:
    needs: [release-pr]
    if: fromJSON(needs.release-pr.outputs.release_pr).state == 'release_required'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Verify Trusted Tag Releaser
        uses: actionutils/trusted-tag-verifier@v0
        with:
          verify: 'actionutils/trusted-tag-releaser@v2'

  # Use the reusable trusted tag workflow for releases if approved
  release:
    needs: [release-pr, verify-releaser]
    if: fromJSON(needs.release-pr.outputs.release_pr).state == 'release_required'
    permissions:
      id-token: write    # Required for signed tags
      contents: write    # Required for release and tag creation
      pull-requests: write # Required for bumpr commenting
      attestations: write # Required for build provenance attestation
      actions: read # Required for SLSA generator
    uses: actionutils/trusted-tag-releaser/.github/workflows/trusted-release-workflow.yml@v2
    with:
      environment: release
      semver-tags-environment: release-semver-tags
      release-notes: ${{ fromJSON(needs.release-pr.outputs.release_pr).release_notes }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
