name: Release Preview Comment

# This workflow posts a comment on PRs with information about the next release version when labeled
# It's designed as a reusable workflow that can be called from other workflows
on:
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to checkout'
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      github-token:
        description: 'GitHub token with pull-requests:write permission'
        required: true

permissions: {}

jobs:
  # Post version bump information comment on PR when labeled
  preview-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
      - name: Post release preview comment
        uses: haya14busa/action-bumpr@v1.11.4
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
