name: Trusted Go Release Workflow

# This workflow creates a secure release for GitHub repositories
# It's designed as a reusable workflow that can be called from other workflows
# It enforces releases only through labeled PRs (bump:patch, bump:minor, bump:major)
on:
  workflow_call:
    inputs:
      ref:
        description: 'The ref to checkout (commit SHA, tag, or branch)'
        required: false
        default: ${{ github.sha }}
        type: string
      draft:
        description: 'Whether to keep the release as a draft'
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        description: 'GitHub token with appropriate permissions'
        required: true
    outputs:
      tag_name:
        description: 'The tag name created or used for this release'
        value: ${{ jobs.version.outputs.tag_name }}
      version:
        description: 'The version number without "v" prefix'
        value: ${{ jobs.version.outputs.version }}
      release_url:
        description: 'URL of the created GitHub release'
        value: ${{ jobs.release.outputs.release_url }}

permissions:
  contents: read

jobs:
  # Version management and tag creation job
  version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Enable OIDC
      contents: write # Tag updates
      pull-requests: write # Post comment
    outputs:
      tag_name: ${{ steps.tag.outputs.value }}
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      # Set up signed tag configuration
      - uses: chainguard-dev/actions/setup-gitsign@v1.4.13

      # Bump version based on PR labels (bump:major,bump:minor,bump:patch)
      - id: bumpr
        uses: haya14busa/action-bumpr@v1.11.4

      # Get tag name from bumpr output only
      - id: tag
        run: |
          if [[ "${{ steps.bumpr.outputs.skip }}" == "true" ]]; then
            echo "value=" >> "$GITHUB_OUTPUT"
            echo "No version bump label found, skipping release."
          else
            TAG="${{ steps.bumpr.outputs.next_version }}"
            echo "value=${TAG}" >> "$GITHUB_OUTPUT"
            echo "Next version: ${TAG}"
          fi

      # Extract version number without "v" prefix (v1.2.3 → 1.2.3)
      - id: extract-version
        if: steps.tag.outputs.value != ''
        run: |
          TAG="${{ steps.tag.outputs.value }}"
          VERSION="${TAG#refs/tags/v}"
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Extracted version: ${VERSION}"

  goreleaser:
    needs: [version]
    if: needs.version.outputs.tag_name != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      attestations: write # needed for provenance
    outputs:
      artifacts: ${{ steps.goreleaser.outputs.artifacts }}
      checksum_file: ${{ steps.checksumtxt.outputs.checksum_file }}
      hashes: ${{ steps.checksumtxt.outputs.hashes }}
      config_exists: ${{ steps.check-config.outputs.config_exists }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - uses: sigstore/cosign-installer@v3.9.2 # installs cosign
      - uses: anchore/sbom-action/download-syft@v0.20.5 # installs syft
      - uses: goreleaser/goreleaser-action@v6 # run goreleaser
        id: goreleaser
        with:
          version: '~> v2'
          args: release --clean --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get checksum file name
        id: checksumtxt
        env:
          ARTIFACTS: ${{ steps.goreleaser.outputs.artifacts }}
        run: |
          checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .name')
          echo "checksum file: ${checksum_file}"
          echo "checksum_file=${checksum_file}" >> "$GITHUB_OUTPUT"
          echo "hashes=$(cat "dist/$checksum_file" | base64 -w0)" >> "$GITHUB_OUTPUT"
      - uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: ./dist/${{ steps.checksumtxt.outputs.checksum_file }}
      # Generate attestations for checksum file itself.
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: ./dist/${{ steps.checksumtxt.outputs.checksum_file }}

      # Binstaller steps
      - name: Check for binstaller config
        id: check-config
        run: |
          if [[ -f .config/binstaller.yml || -f .config/binstaller.yaml ]]; then
            echo "config_exists=true" >> "$GITHUB_OUTPUT"
            echo "Binstaller config found"
          else
            echo "config_exists=false" >> "$GITHUB_OUTPUT"
            echo "No binstaller config found, skipping binstaller steps"
          fi
      - uses: actionutils/trusted-tag-verifier@v0
        if: steps.check-config.outputs.config_exists == 'true'
        with:
          verify: 'binary-install/setup-x@v1'
      - name: Install binstaller
        if: steps.check-config.outputs.config_exists == 'true'
        uses: binary-install/setup-x@v1
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/main/install.sh
          gh_attestations_verify_flags: --repo binary-install/binstaller --cert-identity-regex=.github/workflows/generate-installer.yml@refs/heads/main
      - name: Embed checksums
        if: steps.check-config.outputs.config_exists == 'true'
        env:
          checksum_file: ${{ steps.checksumtxt.outputs.checksum_file }}
        run: binst embed-checksums --mode=checksum-file --file="./dist/${checksum_file}" --version='${{ needs.version.outputs.tag_name }}'
      - name: Generate installer and runner scripts
        if: steps.check-config.outputs.config_exists == 'true'
        run: |
          binst gen --type=installer --target-version='${{ needs.version.outputs.tag_name }}' --output=./dist/install.sh
          binst gen --type=runner --target-version='${{ needs.version.outputs.tag_name }}' --output=./dist/run.sh
      - name: Sign installer and runner with cosign
        if: steps.check-config.outputs.config_exists == 'true'
        run: |
          cosign sign-blob \
            --yes \
            --output-signature ./dist/install.sh.sig \
            --output-certificate ./dist/install.sh.pem \
            ./dist/install.sh
          cosign sign-blob \
            --yes \
            --output-signature ./dist/run.sh.sig \
            --output-certificate ./dist/run.sh.pem \
            ./dist/run.sh
      - name: Upload installer and runner to release
        if: steps.check-config.outputs.config_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload '${{ needs.version.outputs.tag_name }}' \
            ./dist/install.sh \
            ./dist/install.sh.sig \
            ./dist/install.sh.pem \
            ./dist/run.sh \
            ./dist/run.sh.sig \
            ./dist/run.sh.pem
      - name: Attest binstaller scripts
        if: steps.check-config.outputs.config_exists == 'true'
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            ./dist/install.sh
            ./dist/run.sh

  provenance:
    if: needs.version.outputs.tag_name != ''
    needs: [version, goreleaser]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.goreleaser.outputs.hashes }}"
      upload-assets: true # upload to a new release
      upload-tag-name: "${{ needs.version.outputs.tag_name }}"

  release:
    needs: [version, goreleaser, provenance]
    if: needs.version.outputs.tag_name != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for release creation
    outputs:
      release_url: ${{ steps.update_release.outputs.release_url }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ needs.version.outputs.tag_name }}

      - name: Create base verification instructions
        id: create_base_instructions
        run: |
          TEMP_FILE=$(mktemp)
          cat > "$TEMP_FILE" << 'EOF'

          <details>
          <summary>📋 Release Verification Instructions</summary>

          ## Verifying Release Artifacts

          ### Using Cosign

          All release artifacts are signed using [Sigstore](https://sigstore.dev/) and can be verified using [cosign](https://github.com/sigstore/cosign):

          ```bash
          # Download the release assets
          gh release download ${{ needs.version.outputs.tag_name }} --repo ${{ github.repository }}

          # Verify the checksum file signature
          cosign verify-blob \
            --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            --cert "${{ needs.goreleaser.outputs.checksum_file }}.pem" \
            --signature "${{ needs.goreleaser.outputs.checksum_file }}.sig" \
            "${{ needs.goreleaser.outputs.checksum_file }}"

          # Verify checksums of all binaries
          sha256sum --ignore-missing -c "${{ needs.goreleaser.outputs.checksum_file }}"
          ```

          ### Using GitHub Attestations

          All artifacts have [GitHub Attestations](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds) that can be verified:

          ```bash
          # Verify attestations for the checksum file
          gh attestation verify "${{ needs.goreleaser.outputs.checksum_file }}" --repo ${{ github.repository }} --signer-workflow='actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml'
          ```

          EOF
          echo "base_instructions_file=$TEMP_FILE" >> "$GITHUB_OUTPUT"

      - name: Add binstaller instructions
        id: add_binstaller_instructions
        run: |
          BASE_FILE="${{ steps.create_base_instructions.outputs.base_instructions_file }}"
          echo "Binstaller config exists: ${{ needs.goreleaser.outputs.config_exists }}"

          # Close the verification instructions details
          cat >> "$BASE_FILE" << 'CLOSE_VERIFICATION_EOF'

          </details>
          CLOSE_VERIFICATION_EOF

          if [[ "${{ needs.goreleaser.outputs.config_exists }}" == "true" ]]; then
            echo "Adding binstaller instructions..."
            cat >> "$BASE_FILE" << 'BINSTALLER_EOF'

          <details>
          <summary>📦 Installation Scripts</summary>

          This release includes installation scripts generated by [binstaller](https://github.com/binary-install/binstaller):

          - `install.sh` - Downloads and installs the binary
          - `run.sh` - Downloads and runs the binary directly

          ## Verifying Installation Scripts

          Before using the installation scripts, you can verify their authenticity using cosign (signatures) or GitHub Attestations.

          ```bash
          # Download the scripts and their signatures
          gh release download ${{ needs.version.outputs.tag_name }} --pattern "*.sh*" --repo ${{ github.repository }}

          # Verify with cosign (recommended)
          cosign verify-blob \
            --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            --cert install.sh.pem \
            --signature install.sh.sig \
            install.sh

          cosign verify-blob \
            --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            --cert run.sh.pem \
            --signature run.sh.sig \
            run.sh

          # Or verify with GitHub Attestations
          # Verify the install script
          gh attestation verify install.sh --repo ${{ github.repository }} --signer-workflow='actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml'

          # Verify the run script
          gh attestation verify run.sh --repo ${{ github.repository }} --signer-workflow='actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml'
          ```

          ## Using Installation Scripts

          ```bash
          # Install the binary
          curl -sSfL https://github.com/${{ github.repository }}/releases/download/${{ needs.version.outputs.tag_name }}/install.sh | sh

          # Or run directly without installation
          curl -sSfL https://github.com/${{ github.repository }}/releases/download/${{ needs.version.outputs.tag_name }}/run.sh | sh
          ```

          ## One-liner Installation with Verification

          ### Using Cosign (recommended)

          ```bash
          # Set the desired version and script type
          VERSION="${{ needs.version.outputs.tag_name }}"
          SCRIPT="install.sh"  # or "run.sh"
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}"

          # Download and verify with cosign, then execute
          curl -sL "${DOWNLOAD_URL}/${SCRIPT}" | \
              (tmpfile=$(mktemp); cat > "$tmpfile"; \
               cosign verify-blob \
                 --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
                 --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
                 --certificate "${DOWNLOAD_URL}/${SCRIPT}.pem" \
                 --signature "${DOWNLOAD_URL}/${SCRIPT}.sig" \
                 "$tmpfile" && \
               sh "$tmpfile"; rm -f "$tmpfile")
          ```

          ### Using GitHub Attestations

          ```bash
          # Set the desired version
          VERSION="${{ needs.version.outputs.tag_name }}"

          # Install with attestation verification
          curl -sL "https://github.com/${{ github.repository }}/releases/download/${VERSION}/install.sh" | \
              (tmpfile=$(mktemp); cat > "$tmpfile"; \
               gh attestation verify --repo=${{ github.repository }} --signer-workflow='actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml' "$tmpfile" && \
               sh "$tmpfile"; rm -f "$tmpfile")
          ```

          </details>
          BINSTALLER_EOF
          else
            echo "No binstaller config found, skipping binstaller instructions"
          fi

          echo "instructions_file=$BASE_FILE" >> "$GITHUB_OUTPUT"


      - name: Update GitHub Release
        id: update_release
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: |
          TAG_NAME="${{ needs.version.outputs.tag_name }}"

          # Get current release body
          CURRENT_BODY=$(gh release view "$TAG_NAME" --json body --jq '.body')

          # Get final verification instructions
          VERIFICATION_INSTRUCTIONS=$(cat "${{ steps.add_binstaller_instructions.outputs.instructions_file }}")

          # Combine current body with verification instructions
          NEW_BODY="${CURRENT_BODY}${VERIFICATION_INSTRUCTIONS}"

          # Update release with combined body
          RELEASE_URL=$(gh release edit "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --notes "$NEW_BODY" \
            --draft=${{ inputs.draft }})

          echo "release_url=$RELEASE_URL" >> "$GITHUB_OUTPUT"
          echo "Release URL: $RELEASE_URL"

  # https://goreleaser.com/install/#verifying-the-artifacts
  verification-with-cosign:
    needs: [version, release, goreleaser]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.2

      - name: Download assets
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ needs.version.outputs.tag_name }}
        run: |
          gh -R "${GITHUB_REPOSITORY}" release download "${TAG_NAME}"

      - name: Verify checksum signature
        env:
          checksum_file: ${{ needs.goreleaser.outputs.checksum_file }}
        run: |
          cosign verify-blob \
            --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            --cert "${checksum_file}.pem" \
            --signature "${checksum_file}.sig" \
            "${checksum_file}"

      - name: Verify checksum
        env:
          checksum_file: ${{ needs.goreleaser.outputs.checksum_file }}
        run: |
          sha256sum --ignore-missing -c "${checksum_file}"
      - name: Verify installer/runner signatures
        run: |
          if [[ -f install.sh && -f install.sh.sig && -f install.sh.pem ]]; then
            cosign verify-blob \
              --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
              --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
              --cert install.sh.pem \
              --signature install.sh.sig \
              install.sh
          fi
          if [[ -f run.sh && -f run.sh.sig && -f run.sh.pem ]]; then
            cosign verify-blob \
              --certificate-identity-regexp '^https://github.com/actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@.*$' \
              --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
              --cert run.sh.pem \
              --signature run.sh.sig \
              run.sh
          fi
