name: Trusted Go Release Workflow

# This workflow creates a secure release for GitHub repositories
# It's designed as a reusable workflow that can be called from other workflows
# It enforces releases only through labeled PRs (bump:patch, bump:minor, bump:major)
on:
  workflow_call:
    inputs:
      ref:
        description: 'The ref to checkout (commit SHA, tag, or branch)'
        required: false
        default: ${{ github.sha }}
        type: string
      draft:
        description: 'Whether to keep the release as a draft'
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        description: 'GitHub token with appropriate permissions'
        required: true
    outputs:
      tag_name:
        description: 'The tag name created or used for this release'
        value: ${{ jobs.version.outputs.tag_name }}
      version:
        description: 'The version number without "v" prefix'
        value: ${{ jobs.version.outputs.version }}
      release_url:
        description: 'URL of the created GitHub release'
        value: ${{ jobs.release.outputs.release_url }}

jobs:
  # Version management and tag creation job
  version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Enable OIDC
      contents: write # Tag updates
      pull-requests: write # Post comment
    outputs:
      tag_name: ${{ steps.tag.outputs.value }}
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # Set up signed tag configuration
      - uses: chainguard-dev/actions/setup-gitsign@v1.0.1

      # Bump version based on PR labels (bump:major,bump:minor,bump:patch)
      - id: bumpr
        uses: haya14busa/action-bumpr@v1.11.4

      # Get tag name from bumpr output only
      - id: tag
        run: |
          if [[ "${{ steps.bumpr.outputs.skip }}" == "true" ]]; then
            echo "value=" >> $GITHUB_OUTPUT
            echo "No version bump label found, skipping release."
          else
            TAG="${{ steps.bumpr.outputs.next_version }}"
            echo "value=${TAG}" >> $GITHUB_OUTPUT
            echo "Next version: ${TAG}"
          fi

      # Extract version number without "v" prefix (v1.2.3 → 1.2.3)
      - id: extract-version
        if: steps.tag.outputs.value != ''
        run: |
          TAG=${{ steps.tag.outputs.value }}
          VERSION=${TAG#refs/tags/v}
          VERSION=${VERSION#v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

  goreleaser:
    needs: [version]
    if: needs.version.outputs.tag_name != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      attestations: write # needed for provenance
    outputs:
      artifacts: ${{ steps.goreleaser.outputs.artifacts }}
      checksum_file: ${{ steps.checksumtxt.outputs.checksum_file }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - uses: sigstore/cosign-installer@v3.8.1 # installs cosign
      - uses: anchore/sbom-action/download-syft@v0.18.0 # installs syft
      - uses: goreleaser/goreleaser-action@v6 # run goreleaser
        id: goreleaser
        with:
          version: '~> v2'
          args: release --clean --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ls ./dist
      - name: Get checksum file name
        id: checksumtxt
        env:
          ARTIFACTS: ${{ steps.goreleaser.outputs.artifacts }}
        run: |
          checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .name')
          echo "checksum file: ${checksum_file}"
          echo "checksum_file=${checksum_file}" >> $GITHUB_OUTPUT
      - uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: ./dist/${{ steps.checksumtxt.outputs.checksum_file }}
      # Generate attestations for checksum file itself.
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: ./dist/${{ steps.checksumtxt.outputs.checksum_file }}

      # Binstaller steps
      - name: Check for binstaller config
        id: check-config
        run: |
          if [[ -f .config/binstaller.yml || -f .config/binstaller.yaml ]]; then
            echo "config_exists=true" >> $GITHUB_OUTPUT
            echo "Binstaller config found"
          else
            echo "config_exists=false" >> $GITHUB_OUTPUT
            echo "No binstaller config found, skipping binstaller steps"
          fi
      - uses: actionutils/trusted-tag-verifier@v0
        if: steps.check-config.outputs.config_exists == 'true'
        with:
          verify: 'binary-install/setup-x@v1'
      - name: Install binstaller
        if: steps.check-config.outputs.config_exists == 'true'
        uses: binary-install/setup-x@v1
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/main/install.sh
          gh_attestations_verify_flags: --repo binary-install/binstaller --cert-identity-regex=.github/workflows/generate-installer.yml@refs/heads/main
      - name: Embed checksums
        if: steps.check-config.outputs.config_exists == 'true'
        env:
          checksum_file: ${{ steps.checksumtxt.outputs.checksum_file }}
        run: binst embed-checksums --mode=checksum-file --file=./dist/${checksum_file} --version='${{ needs.version.outputs.tag_name }}'
      - name: Generate installer and runner scripts
        if: steps.check-config.outputs.config_exists == 'true'
        run: |
          binst gen --type=installer --target-version='${{ needs.version.outputs.tag_name }}' --output=./dist/install.sh
          binst gen --type=runner --target-version='${{ needs.version.outputs.tag_name }}' --output=./dist/run.sh
      - name: Upload installer and runner to release
        if: steps.check-config.outputs.config_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload '${{ needs.version.outputs.tag_name }}' ./dist/install.sh ./dist/run.sh
      - name: Attest binstaller scripts
        if: steps.check-config.outputs.config_exists == 'true'
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            ./dist/install.sh
            ./dist/run.sh

  release:
    needs: [version, goreleaser]
    if: needs.version.outputs.tag_name != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for release creation
    outputs:
      release_url: ${{ steps.update_release.outputs.release_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.version.outputs.tag_name }}

      - name: Update GitHub Release
        id: update_release
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: |
          TAG_NAME="${{ needs.version.outputs.tag_name }}"

          # Update release
          RELEASE_URL=$(gh release edit "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --draft=${{ inputs.draft }})

          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT
          echo "Release URL: $RELEASE_URL"

  # https://goreleaser.com/install/#verifying-the-artifacts
  verification-with-cosign:
    needs: [version, release, goreleaser]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Download assets
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ needs.version.outputs.tag_name }}
        run: |
          gh -R "$GITHUB_REPOSITORY" release download "$TAG_NAME"

      - name: Verify checksum signature
        env:
          checksum_file: ${{ needs.goreleaser.outputs.checksum_file }}
        run: |
          cosign verify-blob \
            --certificate-identity-regexp '^https://github.com/' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            --cert "${checksum_file}.pem" \
            --signature "${checksum_file}.sig" \
            "${checksum_file}"

      - name: Verify checksum
        env:
          checksum_file: ${{ needs.goreleaser.outputs.checksum_file }}
        run: |
          sha256sum --ignore-missing -c "${checksum_file}"
